#!/bin/sh

case "$1" in
    a)
        mpc-albums | grep --color=auto --fixed-strings \
                   --context "${2:-10}" -- "$(mpc --format '%album%')$"
        ;;
    *)
        mpc playlist | grep --line-number --color=auto --fixed-strings \
                            --line-regexp --context "${2:-10}" -- "$(mpc current)"
        ;;
esac
