#!/bin/sh

play_track()
{
    track="$1"
    if [ "$track" ]; then
        mpc "$extra_opts" play "$track"
    else
        printf '%s failed, track is empty\n' "$0" 2>&1
        exit 1
    fi
}

at_end()
{
    mpc-albums | "$head_tail" -n1 | grep -F -- "$current" >/dev/null
}

next_album()
{
    track=$(mpc-albums | grep -F "$grep_context" -- "$current" | \
                "$head_tail" -n1 | cut -d' ' -f1)
    play_track "$track"
}

skip_num="${2:-1}"
extra_opts="${3:--v}"

# If $skip_num doesn't match the pattern [0-9]*
if ! expr "$skip_num" : '[0-9]*' >/dev/null; then
    printf '%s is not a number\n' "$skip_num"
    exit 1
fi

current=$(mpc -f '%album%' current)

case "$1" in
    p|prev|previous|0)
        grep_context="-B${skip_num}"
        head_tail='head'
        ;;
    *)
        grep_context="-A${skip_num}"
        head_tail='tail'
        ;;
esac

if at_end >/dev/null; then
    printf 'Back to the start...\n'
    mpc "$extra_opts" play 1
else
    next_album
fi
