#!/bin/sh

# This doesn't work in a lot of cases.

skip_num="${2:-1}"
extra_opts="${3:--v}"


at_end() {
    head_tail="$1"
    current="$2"
    mpc_albums | "$head_tail" -n1 | grep -F -- "$current" >/dev/null
}


play_next_album() {
    grep_context="$1"
    current="$2"
    head_tail="$3"

    track=$(mpc_albums | grep "$grep_context" -F -w -- "${current}" | \
                "$head_tail" -n1 | cut -d' ' -f1)
    play_track "$track"
}


current=$(mpc -f '%album%' current)

case "$1" in
    p|prev|previous|0)
        grep_context="-B ${skip_num}"
        head_tail='head'
        ;;
    *)
        grep_context="-A ${skip_num}"
        head_tail='tail'
        ;;
esac

if at_end "$head_tail" "$current" >/dev/null; then
    printf 'Back to the start...\n\n'
    mpc "$extra_opts" play 1
else
    # Log what albums are skipped
    dirname "$(mpc -f '%file%' current)" >> "$mpmm_data"/skipped_albums
    play_next_album "$grep_context" "$current" "$head_tail"
fi

